### PR TITLE
github: Also test on Go 1.20

### PR DESCRIPTION
**Pull request by stgraber**

### CODE REVIEW

**Comment by adamcstephens** [comment]
Almost all users will be using the pre compiled binaries from the registry. What value do you see in testing the older Go version here?

**Comment by stgraber** [comment]
I see two benefits from it, one is it gives us a better view of potential Go compiler bugs by testing on more than one release. That's something that's proved itself useful for Incus in the past. The other is to support an older Go release for the few Linux distributions that would like to ship the provider as a package. Distros are quite often one major release behind so making sure we don't rely on the absolute latest features should help.

I don't really see this as adding testing time given it's done in a test matrix and so is run in parallel by Github. It certainly consumes more test runners but it's not like we pay for those ;)

**Review by adamcstephens — APPROVED** [review]
I have no objection. I am curious what distros beside nixos package terraform providers. ;)

**Comment by stgraber** [comment]
I found some hits around Gentoo derivatives at least. It's definitely not a very common thing but no real harm in supporting it either.

**Pull request merged**
